### ISSUE TITLE
unit test example for coroutines?

### ISSUE THREAD

**Issue by smaddock** [recoilphp/dev#30]
I'm trying to write PHPUnit tests for classes that contain coroutines, and I'm having trouble getting the coroutines to return the value of the full method instead of the just nested yielded function. I've tried calling `current()` on the results, or just putting it in a `foreach` loop, but I'm only getting the value of the yielded line inside the method, not the result of the method itself. Are there any examples of how to run unit tests on coroutines without spinning up the Recoil kernel? If I'm not being clear enough let me know and I can post an example.

**Comment by jmalloc** [comment]
If I understand correctly, you'd essentially need to implement the same behaviour as the Recoil kernel (or a subset thereof) in order to "run" coroutines in this way. Is there any reason you can't spin up the kernel in the test? Please post an example and I'll do my best to help out.

For what little it's worth / disclaimer, I haven't written tests using PHPUnit in many years ;) This repo includes an integration with a testing framework called [peridot](https://github.com/peridot-php/peridot), which allows writing test functions that are themselves coroutines. Unfortunately, it seems that Peridot is unmaintained.
